//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication8.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mark
    {
        public int SubjectId { get; set; }
        public int StudentId { get; set; }
        public double Marks { get; set; }
        public string Subject_Name { get; set; }
    
        public virtual subject subject { get; set; }
        public virtual student student { get; set; }
    }
}
